### PR TITLE
[prometheus-operator] add runbook URL to Alert

### PR DESCRIPTION
**Pull request by Sayrus**

### CODE REVIEW

**Review by frgaudet — APPROVED** [review]

**Review by jbfavre — APPROVED** [review]
Wouldn't be worth writing down run book for other Prometheus related alerts at the same time ?
I'm thinking about `PrometheusMissingRuleEvaluations` which happened already

**Comment by Sayrus** [comment]
> Wouldn't be worth writing down run book for other Prometheus related alerts at the same time ?
> I'm thinking about `PrometheusMissingRuleEvaluations` which happened already

I'm fine with that but there is no quick win on `PrometheusMissingRuleEvaluations`. Unless we severely undersize Prom (as in Yandex), CPU / RAM bumping does not work.
What would you want to document there?

**Comment by jbfavre** [comment]
> Unless we severely undersize Prom (as in Yandex), CPU / RAM bumping does not work.
> What would you want to document there?

I was thinking about CPU/RAM bump, which lookes like the only solution we used so far :thinking:

**Comment by Sayrus** [comment]
> > Unless we severely undersize Prom (as in Yandex), CPU / RAM bumping does not work.
> > What would you want to document there?
> 
> I was thinking about CPU/RAM bump, which lookes like the only solution we used so far thinking

@melchiormoulin I remember that you handled the last alert on GCP. What was the fix? Do you have any quick win on this?

**Comment by melchiormoulin** [comment]
The fix was to fix the query and not to bump CPU or RAM.

**Pull request merged**
